---
- name: Configurar la máquina virtual
  hosts: all
  become: yes
  tasks:
    - name: Actualizar apt y instalar Nginx
      apt:
        update_cache: yes
        name: nginx
        state: present

    - name: Iniciar y habilitar Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Descargar Grafana
      get_url:
        url: https://dl.grafana.com/oss/release/grafana_7.5.10_amd64.deb
        dest: /tmp/grafana_7.5.10_amd64.deb

    - name: Instalar Grafana
      apt:
        deb: /tmp/grafana_7.5.10_amd64.deb
        state: present

    - name: Iniciar y habilitar Grafana
      systemd:
        name: grafana-server
        state: started
        enabled: yes
        
    - name: Descargar node_exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: Extraer node_exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /usr/local/bin/
        remote_src: yes

    - name: Crear usuario para node_exporter
      user:
        name: node_exporter
        shell: /usr/sbin/nologin

    - name: Crear servicio systemd para node_exporter
      copy:
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter-1.3.1.linux-amd64/node_exporter

          [Install]
          WantedBy=default.target
        dest: /etc/systemd/system/node_exporter.service
        mode: '0644'

    - name: Iniciar y habilitar node_exporter
      systemd:
        name: node_exporter
        state: started
        enabled: yes

    - name: Instalar Prometheus
      apt:
        name: prometheus
        state: present

    - name: Iniciar y habilitar Prometheus
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Crear directorio para Prometheus
      file:
        path: /etc/prometheus
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Configurar prometheus.yml
      copy:
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['192.168.56.10:9090']

            - job_name: 'node'
              static_configs:
                - targets: ['192.168.56.10:9100']
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Reiniciar y habilitar Prometheus
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
